evervault/evervault-js

lib/v1/config.js, lib/v1/index.js
Cage playground in staging cannot use the React SDK because the production API URL is hard coded in the Javascript SDK config.
Adding a path to the constructor to accept env var as the keys url path, and passing that through to the config.
=> Adding new field to SDK constructor to accept env var

package.json
Currently pointing at nonexistent index.js at top level
Pointed main at lib/v1/index.js
=> fix: updating main script in package.json

lib/v1/core/inputs.js, lib/v1/index.js, lib/v1/utils/calculateHeight.js, lib/v1/utils/constructSource.js, package-lock.json, package.json
Add support for [evervault-inputs style updates. ](https://github.com/evervault/evervault-inputs/pull/22)
See linked PR for details. 
The second argument of `evervault.inputs` now supports `settings: String || Object`. A string is passed if only a theme is required, (`material`, `minimal`). An object containing a `theme: String` key-value is passed if custom styles are required. Supported styles are: 
- primaryColor
- errorColor
- labelColor
- inputBorderColor
- inputTextColor
- inputBackgroundColor
- inputPlaceholderColor
- inputBorderRadius
- inputHeight
- height
=> Add support for evervault-inputs custom styling

lib/v1/utils/datatypes.js
Arrays are not supposed to be stringified and then encrypted. They should still be arrays, but every element should be encrypted.
Changed `isEncryptable` to match the NodeJS SDK.
=> Array elements are now encrypted rather than entire arrays

lib/utils/constructSource.js, lib/v2/config.js
Need to use the v2 endpoint for inputs to have them be app tenanted
=> fix: Use v2 inputs

.github/workflows/release.yml, lib/v1/index.js
When testing file encryption a race condition came up where two objects are encrypted in quick succession.
This was fixed in the v2 sdk but not backported to the v1 sdk.
Backported the fix to the v1 sdk
Also had to bump the version of node in the workflow because the semantic release bot was refusing to run with node < 18
=> fix: backport race condition fix to v1

lib/v1/index.js
Backporting fix was not compatible with v1 inputs due to its raw use of `evervault.loadKeys()`
Re-added the datatype isDefined check to encrypt in the v1 sdk
=> Readd datatype isDefined check

README.md
A new setting has been added to Inputs to support overwriting the default expiration date placeholder (MM/YY)
Updated readme
=> docs: adding expirationDatePlaceholder for inputs

lib/v1/config.js, lib/v1/core/http.js, lib/v1/index.js, lib/v2/config.js, lib/v2/core/http.js, lib/v2/index.js
We no longer want to report metrics back to Evervault in this way
Removed calls to metrics
=> fix: removing call to metrics

.github/workflows/deploy-base.yml, .github/workflows/deployment.yml
Actions still not working because the yaml isn't right yet. 
See https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations and the note about environments
- Use environments for bucket and cloudfront secrets
- Use organisation secrets for AWS credentials
=> Fix workflow environments

README.md
Incorrect value used in README for `labelWeight`
- Updated value
=> doc: update docs for label weight

lib/core/inputs.js
We have had a few customers recently contact us with problems around setting the iframe height. Because iframes are their own document, they unfortunately don't have a native "height: auto" property that allows it to behave as if it's part of the document it's embedded in.
We now support various styling features that alter the height of the iframe as well as conditionally showing the error message. Requiring customers to set a specific height in px to cater for this is not ideal.
Support automatically handling calculation of the iframe height by listening for a message from the Inputs iframe that fires when ever there are DOM changes. See https://github.com/evervault/evervault-inputs/pull/56.
```
evervault.inputs("ev-inputs", {
height: "auto",
});
``` …
=> Support auto setting height of inputs frame

lib/core/crypto.js, lib/curves/base.js, lib/main.js, lib/utils/concatUint8Arrays.js, lib/utils/crypto.js, lib/utils/datatypes.js, lib/utils/encoding.js, package.json, pnpm-lock.yaml, test/encryption.test.js
Should not be relying on the node js polyfill for Buffer
Replaced with the `uint8arrays` helper library as Buffer is a superclass of that anyway. The npm package `uint8arrays` is better maintained and browser compatible.
=> [ETR-650] Replace Buffer Polyfill

lib/core/crypto.js
Bytes from encrypted files are not a string
Treat them as bytes
=> fix: bytes are not a string

.github/workflows/push.yml
Buckets are not Cloudfront Distributions
Use Cloudfront instead
=> Buckets are not Clouldfront

.github/workflows/release.yml
Need to deploy releases to productions
Created a new github workflow that will build and deploy the SDK in production for a Github release
The process of creating a release is yet to be automated, but manually the process would be:
1. Merge the version bump PR created by `changeset actions`
2. Pull and run `changeset tag`, then push the tags
3. Create the release with either `gh release create` or the Web UI using the previously created tags.
=> Add Release workflow draft

.changeset/seven-carpets-know.md, packages/browser/lib/config.ts, tsconfig.json
Typing the config file seems like a good idea.
Rename config.js to config.ts and give the functions type annotations. That's it.
=> [ETR-851] Rename Config to Typescript

.github/workflows/push.yml, .github/workflows/release.yml
Inputs not working because the workflows use the wrong names for some secrets
Use the correct names
=> Use the correct names for secrets in Github Actions

.changeset/famous-pumpkins-applaud.md, packages/browser/lib/core/forms.js
Nobody should be using Forms now
Nobody.
But someone might be using it anyway, I don't know.
- Add the `@deperecatated` tag to the module
- JSDoc typings: gave up and used any
- Added a console.error call if the register function actually finds a form element that it hooks into it. If a customer is using forms, we wanna know.
Actually deleting this function will require a v3.
=> [ETR-883] Deprecate Forms module

.changeset/wet-items-occur.md, packages/browser/lib/core/inputs.ts
types
Rename inputs from `.js` to `.ts`. Note that the file still requires stricter null checking for more graceful errors, but that is a bit of a behavior change for a minor version.
=> [ETR-882] Convert Inputs Module to Typescript

.github/workflows/push.yml, .github/workflows/release.yml
Disabled the deployment CI for the inputs package until https://github.com/evervault/evervault-inputs is archived
Reenable the deployment steps for CI once the old repo is archived.
=> Reenable CI for Inputs

.github/workflows/build-and-test.yml, .github/workflows/push.yml, package.json, pnpm-lock.yaml
pnpm and turbo a little out of date, and new pnpm lockfile version dropped as well.
- Update `pnpm` locally to 8.6
- Update workflows to use `pnpm` 8.6
- Update `pnpm-lock.yaml` to lockfile version 6.1
- Update `turbo` to 1.10.0
=> Update PNPM Deps (pnpm 8.6, lockfile 6.1)

.changeset/silly-hairs-smile.md, packages/inputs/src/index.js
CodeQL is informing us of a potential CSRF/Redirect vulnerability via the `fontUrl` property. 
Sanitize and reconstruct the `fontURL` so it can only point to Google Fonts, and log an error if the `fontUrl` is not a valid Google Fonts endpoint. This is close to a breaking change, but we have only ever promised that Google Font's will work with our custom fonts feature. Failure will simply mean that the font url is not inserted.
=> [ETR-889] Sanitize Font URL

.github/workflows/aws-generic-deploy-inputs.yml
Inputs deploy command was wierd
Replace pipe operator with `&&`
=> fix: inputs upload

.github/workflows/push.yml, package.json
Version action is not updating `pnpm-lock`
Make a custom version script to run `pnpm install` alongside the version command.
=> Update lockfile when versioning

.changeset/olive-foxes-tickle.md, packages/inputs/src/index.js
Firefox does not support `window.onload`
Using window.addEventListener instead
=> fix: fix onload event in firefox

.changeset/stupid-insects-occur.md, packages/inputs/src/styles.css
Requested by Stitch.
[Slack thread](https://evervault.slack.com/archives/C04BTBHRYCV/p1685443320523839)
Use primary color for label when the input is focused.
=> Use primary-color instead of label color when focused for material theme

.github/workflows/push.yml, .github/workflows/release.yml, README.md
Production releases are currently a somewhat manual process, requiring multiple commands per release per package(!). It's been reasonably well documented in the readme, but I'm now confident enough that we can automate it reasonably efficiently.
- GH releases now created alongside deployments/publishing
- Workflow is triggered when tags created by changeset are created
- Pull request merges of new version create and push changeset tags
This should all mean that merging the "Version packages" PR created by `changesets/action` is all that's needed to release to production.
=> Automate Deployments and releases

.github/workflows/release.yml
Release workflow has incorrect syntax
Put the `action-gh-release` action in a job step rather then a job, so it knows it's an action and not a reusable workflow (Thanks, Github!)
=> Release YML fix

.github/workflows/build-and-test.yml
Build and test workflow doens't always work since build happens after tests and format checks
Move build up the order after install, before test, format and typecheck
=> Rework Build Order

.changeset/rotten-badgers-reply.md, packages/inputs/.prettierignore, packages/inputs/postcss.config.js
PostCSS wasn't detecting the `postcss.config.mts` file. I'm not sure if it supports `mts` extension.
Change it to a `.js` file.
This also includes a `.prettierignore` file for inputs to ignore formatting/checking formatting for compiled files in the `dist` dir.
=> Change PostCSS config from .mts to .js

.changeset/angry-toys-listen.md, e2e-tests/inputs/tests/events.spec.js, packages/inputs/src/index.ts
8 number BIN's are allowed by all card providers expect Amex
- Update BIN extractor to use 8 number BIN if not Amex
=> BIN number should be 8 if not amex

.changeset/slow-eggs-fly.md, README.md, packages/inputs/index.html, packages/inputs/src/index.ts
On some browsers, users are seeing the uncustomised form for a short moment before customisations are applied to it.
This PR introduces a change where the card form is hidden by default, then unhidden once all customisations have been applied to it.
=> [hotfix] Prevent short lag where users were seeing the uncustomised form

.github/workflows/aws-generic-deploy-inputs.yml
Inputs assets are not properly invalidated with CloudFront when a new version of inputs is deployed.
Invalidate the entirety of /v2
=> Invalidate assets in cloudfront when a new 

.changeset/cyan-goats-battle.md, packages/browser/lib/config.ts, packages/browser/lib/core/http.ts, packages/browser/lib/main.ts, packages/browser/test/basic.test.ts
The browser SDK was incorrectly resolving its context, defaulting to inputs in every case.
Add function to check context against the current window
=> Fix: Correct check for inputs context in browser SDK

.github/workflows/npm-publish.yml, .github/workflows/release.yml
NPM publish workflow uses pnpm's git checks, which assert that the branch must be `master|main`. We publish using tags, which is causing pnpm to block the release.
Disable checks on git branch
=> Fix npm publish workflow

.changeset/shy-taxis-allow.md, packages/inputs/index.html
to be compatible with webpages rendered with the `normal` color scheme
add normal to the meta tag
=> add normal to the inputs color scheme

.changeset/young-pets-sit.md, packages/browser/lib/core/inputs.ts, packages/browser/lib/main.ts, packages/inputs/src/app/RevealManager.ts, packages/inputs/src/index.html, packages/inputs/src/reveal.html
need to be able to serialize headers for requests
fixes a bug where reveal displayed weirdly on darkmode
turn headers in to a normal object if they're a `Headers`
change meta theme
=> fix header serialization and dark mode

.changeset/eighty-jars-float.md, packages/browser/lib/core/inputs.ts, packages/inputs/src/app/index.ts
Safari doesn't support serializing errors (they are the one browser not to do this) which breaks our promise throwing.
Serialize the error manually. Then we try and reconstruct in to the correct error type if its available in the current context
=> make errors serialize in safari

.changeset/ninety-lions-check.md, packages/react/lib/main.tsx
Needs to work without custom config
Use a '?'
=> handle undefined custom config

.changeset/smooth-kids-float.md, packages/inputs/src/app/styles.css
The `material` theme was applying `display: flex` which was overriding the `.hide` class.
Restrict the material theme CSS selector to  input groups that don't have the hide class.
=> Prevent material theme from overriding .hide class

.changeset/moody-forks-perform.md, packages/inputs/src/app/styles.css
Sling provided some feedback on their customisations.
The following changes have been implemented:
- Add `-webkit-font-smoothing: antialiased` to the form
- remove unnecessary padding on `.form-group`
=> Various minor improvements to the material-sling theme

.changeset/odd-fireants-behave.md, e2e-apps/browser/src/scaffold-test-single.js, packages/browser/lib/core/http.ts, packages/browser/test/basic.test.ts
`Decrypt` was returning the `data` attribute of the decrypt response when `data` didn't exist. Unit tests made this behaviour pass tests.
Remove casting to `{ data: ... }`
=> Fix an invalid cast in the decrypt function

.github/workflows/release.yml
- The release flow for ui components was using staging keys.
- The flow wasn't scoped to tags for the @evervault/ui-components package.
=> Update release flow for ui-components

.github/workflows/build-and-test.yml, .github/workflows/pull-request.yml
The Github Action build and test workflow was requiring TESTS_API_KEY, however, it didn't actually use it.
=> Remove TESTS_API_KEY from workflows

packages/react/package.json, packages/themes/package.json, packages/types/package.json, pnpm-lock.yaml
Publish step failed because themes and types are internal packages and they were listed as dependencies.
=> Move types and themes to devDependency for react

.changeset/two-zoos-reflect.md, packages/eslint-config-custom/index.js, packages/react/package.json
Yarn does not support package.json `bundledDependencies`.
We had added `bundledDependencies` in the first place because eslint was erroring on themes and types being devDependencies instead of dependencies. This won't work though as neither of these are published packages and instead are bundled by the SDK. So we have changed the eslint error to a warning.
=> Remove bundledDependencies from react package.json

.changeset/weak-walls-provide.md, packages/react/vite.config.mts
The Types from the internal types, themes, and browser packages were being stripped out.
Update the dts config to bundle them.
=> Bundle dependency types with the react package

.changeset/stupid-buttons-drop.md, packages/react/lib/main.tsx
The React SDK didn't have a decrypt function.
=> Add decrypt function to react SDK

.changeset/chilly-bees-lick.md, packages/browser/lib/ui/card.ts, packages/react/lib/ui/Card.tsx, packages/themes/minimal.ts, packages/types/uiComponents.ts, packages/ui-components/src/Card/CardHolder.tsx, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/translations.ts, packages/ui-components/src/Card/types.ts, packages/ui-components/src/Card/utilities.ts, packages/ui-components/src/index.css, packages/ui-components/src/utilities/useForm.ts
Browsers do not allow input auto completes to pass from the parent frame down into the child iframe. This meant that when prompted on a 'name' field in the parent document, the auto complete would not fill out the card number, expiry or cvc.
The only way to fix this at the moment is to provide functionality for users to render a 'name' field inside of the component iFrame. This PR adds a `fields` option to the Card component which allows users to define which fields they want to display and supports a 'name' field.
```js
const card = evervault.ui.card({
fields: ['name', 'number', 'expiry', 'cvc'],
})
```
This PR also includes a new `isComplete` field on the card payload which indicates if the card has been correctly filled out. As well as a new `complete` event which will fire once the …
=> Support displaying card holder name field via fields argument

.changeset/mighty-waves-hope.md, packages/react/lib/ui/Card.tsx, packages/react/lib/ui/Pin.tsx
Some UI component options weren't available as React props.
- Adds autoFocus prop for Card and Pin Component.
- Adds mode prop for Pin component.
- Adds inputType prop for Pin component.
=> Add missing React props for UI component options

.changeset/rotten-forks-trade.md, packages/ui-components/src/utilities/useForm.ts
We were setting form values by passing the updated form state to the `setValues` function call provided by React `useState`. This was causing a race condition for some browsers when using auto complete functionality for card data.
Use a callback instead to ensure when the values are updated to avoid race conditions.
=> Use callback to set form values

.changeset/rude-candles-play.md, e2e-tests/ui-components/tests/cardDetails.spec.js, examples/custom-theme/src/main.ts, packages/ui-components/src/Card/CardCVC.tsx, packages/ui-components/src/Card/CardExpiry.tsx, packages/ui-components/src/Card/CardNumber.tsx, packages/ui-components/src/Pin/index.tsx, packages/ui-components/src/utilities/useMask.ts
The onChange handler for inputs was being called in a usEffect call which checks if the value was truthy. This was preventing the handler being called when it was being cleared as the empty value would be falsey. This was to prevent useEffect firing the change handler multiple times.
Instead the handler is now passed directly through to the useMask hook rather than doing it inside of an effect.
=> Fix change event handler when clearing inputs

.changeset/polite-moles-jog.md, packages/inputs/src/app/RevealManager.ts
Inputs Reveal uses `innerHTML` to set the response values which is vulnerable to XSS.
Use `textContent` instead.
=> Prevent XSS in inputs reveal

.changeset/funny-queens-join.md, .env.example, examples/forms/index.html, packages/browser/lib/main.ts
The formUuid will need to passed in for a third party form so the JS knows in the response from the API to target this form.
- Pass formUuid as a form parameter
- Find the formUuid in the response from the API
=> Eoin/etr 1668 third party form will need to pass in the form UUID

.changeset/twenty-meals-fail.md, packages/inputs/src/app/styles.css
Hey team
We're reworking some designs at Sling and just need to slightly tweak the spacing of some inputs on `material-sling`
Won't merge until we deploy the new version on our end as well.
=> Sling: Update material-sling spacing for redesign

.changeset/red-buttons-refuse.md
We're introducing a new `acceptedBrands` option and a new `unsupportedBrand` translation. This requires a bump of the browser sdk.
Create changeset
=> Add changeset for browser sdk

.changeset/smart-waves-crash.md
We're introducing a new acceptedBrands option and a new unsupportedBrand translation. This requires a bump of the browser sdk.
Add changeset
=> Add changeset for React SDK

packages/card-validator/vite.config.mts
vite is adding `"types": "0.0.0"` dep to our package json which isn't what we want
=> bundle internal types package in distribution

.changeset/ten-rules-collect.md, packages/card-validator/package.json, pnpm-lock.yaml
changeset didn't apply previously and release never happened. We actually want to publish this again now that we can't use shared packages in react native
add back the distribution stuff to package.json
=> Release new card validators version

.github/workflows/deploy-ui-components.yml, .github/workflows/npm-publish.yml
pnpm is releasing a minor every day
stop downloading the latest pnpm ver and use what's in package json
=> remove pnpm version from actions

.changeset/four-ducks-smile.md, packages/ui-components/src/Form/index.tsx
Form render select component must update its internal state
- Make `SelectRenderer` its own functional component with state
=> fix: select component state update

.changeset/giant-maps-tickle.md, packages/react-native/android/build.gradle, packages/react-native/android/gradle.properties
Kotlinx imports failing
resolves ETR-2117
Added coroutines deps, not sure why these aren't needed on react native 74
=> Fix RN 71 android build

.env.example, e2e-apps/browser/package.json, e2e-apps/browser/src/scaffold-test-object.js, e2e-apps/browser/src/scaffold-test-single.js, e2e-apps/decrypt-backend/index.mjs, e2e-tests/browser/package.json, e2e-tests/browser/playwright.config.ts, e2e-tests/browser/tests/basic.spec.ts, e2e-tests/inputs/playwright.config.js, e2e-tests/ui-components/playwright.config.js, e2e-tests/ui-components/tests/reveal.spec.js, packages/browser/vite.config.mts
Our tests are in need of a bit of love and have started failing both in CI and locally. We also have some duplication of environment variables which makes configuring the repo locally painful.
- Removes duplicate environment variables
- Always source the root `.env` when running tests so that they will work whether you are running them from root or inside of the package.
- Fix browser tests
=> Cleanup environment variables and tests

e2e-apps/browser/package.json, e2e-apps/decrypt-backend/package.json, e2e-tests/browser/package.json, e2e-tests/inputs/package.json, e2e-tests/ui-components/package.json
Turbo requires either no version key, or a valid version key. However, if no version key is set, then changeset adds "version": null which is an invalid version.
=> Add version key to test packages

.github/workflows/push.yml
Change set is doing a push which is triggering husky to run all the linting
=> Skip husky hooks for change set action

.changeset/sweet-baboons-remain.md, packages/react-native/src/components/Card/utilities.ts
Causing issues with payment processors
Remove spaces before encryption occurs
=> Remove spaces from CC Num before encryption

.changeset/chilled-spiders-give.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/browser/lib/ui/card.ts, packages/react/lib/ui/Card.tsx, packages/types/uiComponents.ts, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/types.ts, packages/ui-components/src/Card/utilities.ts
Some users want functionality to automatically progress the browser focus to the next input when filling out card details. This adds a new `autoProgress` option to the `Card` component. When filling out a card number, if they enter a valid card number, the browser focus will move to the expiry field. The same applies to the expiry field, when it is valid, the focus moves to the cvc.
```js
ev.ui.card({ autoProgress: true })
```
=> Add autoProgress option to Card component

packages/browser/lib/ui/threeDSecure.ts
It is crucial to ensure that the session outcome is fully saved before unmounting the frame and dispatching the completion event. Failing to do so previously caused a race condition, where users could access session data before it was fully finalised.
This PR makes the request to update the session outcome synchronous.
=> Synchronously update session outcome before unmounting 3DS frame

.changeset/wild-apes-mate.md, e2e-tests/ui-components/tests/cardDetails.spec.js, examples/collect-card-details/src/main.ts, packages/browser/lib/ui/card.ts, packages/browser/lib/ui/evervaultFrame.ts, packages/shared/src/useForm.ts, packages/types/uiComponents.ts, packages/ui-components/src/Card/index.tsx
The `validate` method on the card component can be used to manually trigger validation to display any error messages inside of the component. Due to everything having to be done via messaging in the iframe this is an async call and does not immediately provide results when called. The `validate` method was not intended to provide results but instead to simply cause any error messages to be shown, when the user hasn't interacted with the inputs. e.g Submits without filling out any details. 
It could be useful however, to provide some way for users to run logic after validation has occurred. In an ideal world, we would simply make this method return a promise which can be awaited, however, unfortunately that would be a breaking change and so isn't an option. This PR adds a new `validate` …
=> Add validate event

packages/react-native/package.json, pnpm-lock.yaml
Presently if you make a change to the SDK while running the example app, the example app shows a "reloading" toast. In reality nothing happens because the SDK JS dist hasn't been rebuilt.
This change should make the devexp less painful.
Add a script to the SDK so it can be rebuilt on changes. This can be run in a seperate terminal to the example app.
Unfortunately this will cause the example app's bundler to throw "files not found" module resolution errors during the rebuild. Since the dist dir is deleted before the rebuild.
=> Add hotreloading to react-native sdk

.changeset/nervous-drinks-cheat.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/ui-components/src/Card/CardExpiry.tsx, packages/ui-components/src/Card/translations.ts
Our expiration field expects a format of `[0-1][1-9]`. This means if a user has an expiration date for September they must enter `09` rather than simply `9`.
Automatically pad the expiration for values between 2 - 9. Luckily imask has a built in option for this.
=> Autopad expiry field when users enter a value between 2 - 9

.changeset/tricky-beers-march.md, packages/card-validator/brands.ts, packages/card-validator/test/validate-number.test.ts, packages/react-native/src/components/Card/types.ts, packages/types/uiComponents.ts
Adding support for encrypting UATP cards.
- Add new validator for UATP cards, they begin with 1 and are 15 digits.
=> feat: add UATP support

package.json, pnpm-lock.yaml
https://github.com/evervault/evervault-js/actions/runs/10771407623/job/29868666932
The CI hanging during e2e:tests with no error logs, I think it might be related to this: 
https://github.com/vercel/turborepo/issues/8281
Bump to newer turbo version 2.1.1 to see if it resolves
=> Bump turbo

.changeset/shiny-vans-call.md, .changeset/spotty-dryers-promise.md
One changeset mentions the addition of ThreeDSecure.Modal and then the next removes it. We should just never mention it at all.
Update first changeset and then remove the second one that mentions removing the modal. I think this will work so that there's only one change when we release
=> Updating redundant changesets 

.changeset/late-dogs-dance.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/shared/src/useForm.ts, packages/ui-components/src/Card/CardCVC.tsx, packages/ui-components/src/Card/CardNumber.tsx, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/utilities/useMask.ts
- Currently if a user enters an amex card and only enters 3 digits in the CVC it is correctly marked as invalid, however, if the user then switches to a Visa card, the CVC is still marked as invalid even though a 3 digit CVC should be considered valid.
- If a user enters an amex card and a 4 digit CVC of '1234' and then switches to a Visa card the CVC mask is updated and it is truncated to '123', however, the underlying value for the CVC will still be '1234' when it should b changed to '123'.
This PR also improves our tests slightly to use the decrypt API to assert that the encrypted values match the original card values.
=> Rerun validation for invalid card fields on changes

.changeset/loud-pans-attend.md, packages/react-native/package.json, packages/react-native/src/__tests__/index.test.tsx, packages/react-native/src/components/Card/utilities.test.ts, packages/react-native/src/components/Card/utilities.ts
Card number is being formatted even if it isn't mounted, which leads to a `TypeError`
- Check registered fields set to see if the card number is mounted before formatting
- Add tests for change payload callback function in react native
=> Fix TypeError on card number if not mounted

.changeset/silly-penguins-chew.md, packages/react-native/src/components/Card/utilities.ts, packages/react-native/src/components/useForm.tsx
- Currently if a user enters an amex card and only enters 3 digits in the CVC it is correctly marked as invalid, however, if the user then switches to a Visa card, the CVC is still marked as invalid even though a 3 digit CVC should be considered valid.
- If a user enters an amex card and a 4 digit CVC of '1234' and then switches to a Visa card the CVC mask is updated and it is truncated to '123', however, the underlying value for the CVC will still be '1234' when it should b changed to '123'.
=> fix: cvc validation not updating when card brand changes

.changeset/cold-planets-drop.md, packages/ui-components/src/Card/CardExpiry.tsx, packages/ui-components/src/Card/CardNumber.tsx, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/utilities.ts, packages/ui-components/src/utilities/useMask.ts
Currently the `autoProgress` option will cause the browser focus to automatically progress to the next field once the current field becomes valid. Users have given feedback that this behaviour can feel inconsistent. e.g If a user enterers an invalid card number it wont auto progress and an error wont be shown until the user focuses on the next input.
This PR changes the approach to autoProgress to be based entirely on the input mask instead of validation. This means for card numbers, focus will switch to the expiration field as soon as the user has entered a number that matches the current input mask. If the entered number is invalid, an error will be shown as the focus moves to the expiry.
Note: This is only considered a minor change as the `autoProgress` option is not a documented …
=> autoProgress based on mask instead of validation

.changeset/five-deers-whisper.md, packages/react/lib/ui/useThreeDSecure.ts
Context: https://evervault.slack.com/archives/C05TBHREAG7/p1731332793569229
Unmount the 3DS component on error/failure
Modal renders, errors, doesn't re-render, no subsequent patch calls
Modal renders, errors, re-renders, subsequent patch calls
=> Unmount 3ds instance on error

packages/card-validator/test/validate-expiry.test.ts
Test is using actual time and so when we hit december it was incrementing the month to 13 and failing.
Update to check if month is greater than 12 and then adjust month and year accordingly.
I also ran prettier on the test file
=> Fix validation test

.changeset/famous-kiwis-drop.md, packages/ui-components/src/ThreeDSecure/BrowserFingerprint.tsx
We're getting 400s from Cardinal and presumably other ACSs on account of incorrect naming on the 3ds Method form
=> Fix method url form field

.changeset/wet-peaches-cry.md, examples/collect-card-details/src/main.ts, packages/browser/lib/ui/card.ts, packages/card-validator/index.ts, packages/card-validator/test/validate-expiry.test.ts, packages/react/lib/ui/Card.tsx, packages/shared/src/useForm.ts, packages/types/uiComponents.ts, packages/ui-components/src/Card/CardCVC.tsx, packages/ui-components/src/Card/CardExpiry.tsx, packages/ui-components/src/Card/CardHolder.tsx, packages/ui-components/src/Card/CardNumber.tsx, packages/ui-components/src/Card/index.tsx
Some users have requested functionality to track interactions with individual fields inside of the Card component. This PR introduces 4 new events for the Card component. `focus`, `blur`, `keyup` and `keydown`. These events hook into the corresponding native events for each input, however, it's important that we don't provide the original event which would allow users to gain access to plain text data. Instead we pass an object which includes the field the event originated from, as well as the same card data payload that is sent with the `change` event.
e.g 
```
{
field: "number",
data: {
card: {
name: "",
brand: "visa",
localBrands: [],
bin: "42424242",
lastFour: "4242",
number: "ev:QkTC:WXkiIR/el/Sihcpd:AwBL9S7F91yMdpl2kKYY8tgEJJWGQbiyOX4ciF+arpdO:Q96nNPbHVNenK1NkAAIhaElyfL3u0IDyjrQhjFNP …
```
=> Add events for Card component field interactions 

.changeset/loud-kids-bake.md, e2e-tests/ui-components/tests/threeDSecure.spec.js, examples/three-d-secure/src/main.ts, packages/browser/lib/ui/threeDSecure.ts, packages/react/lib/ui/ThreeDSecure.tsx, packages/react/lib/ui/useThreeDSecure.ts, packages/types/uiComponents.ts, packages/ui-components/src/ThreeDSecure/index.tsx, packages/ui-components/src/ThreeDSecure/types.ts, packages/ui-components/src/ThreeDSecure/utilities.ts
> [!IMPORTANT] 
> Currently blocked by API requirements.
Some users only want to use frictionless 3DS and want to fail if a challenge is requested. This adds support for a new `failOnChallenge` option.
It can either be set to a boolean or a function which returns a boolean or promise that resolves to a boolean.
```js
const tds = evervault.ui.threeDSecure('session', {
failOnChallenge: true
})
tds.on('failure', () => {
console.log('failed')
})
// or
const tds = evervault.ui.threeDSecure('session', {
failOnChallenge: async () => {
console.log('3DS was challenged')
return false
}
})
```
=> Add failOnChallenge option to 3DS

packages/browser/lib/ui/googlePay.ts, packages/types/uiComponents.ts, packages/ui-components/src/GooglePay/index.tsx, packages/ui-components/src/GooglePay/types.ts, turbo.json
CAPI has separate config in Staging and Prod. When google pay targets the 'TEST' environment, it uses the Staging config. This means it will always error in Prod. We have two options, implement both sets of config in CAPI Prod and allow users to set 'TEST' | 'PRODUCTION', or remove the choice entirely so that only the relevant config for the given environment can be targeted.
For now, we'll take the easy route. I can see in time that we might go the other way - it is probably beneficial if users can test their integration without executing real transactions.
Remove the config.environment field from GooglePayOptions, set the value based on the environment when creating the paymentsClient.
=> Infer Google Pay environment from deployment environment

.changeset/chilly-kiwis-know.md, .github/workflows/build-and-test.yml
Release failed because the build artifact isn't uploaded.
=> Fix EQL release job

packages/eql/CHANGELOG.md, packages/eql/package.json
Latest release attempt broke with:
```
npm ERR! code E422
npm ERR! 422 Unprocessable Entity - PUT https://registry.npmjs.org/@evervault%2feql - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/evervault/evervault-js" from provenance
```
=> Add repository object to package.json

.changeset/heavy-paws-walk.md, e2e-tests/ui-components/tests/cardDetails.spec.js, examples/collect-card-details/src/main.ts, packages/browser/lib/ui/card.ts, packages/react/lib/ui/Card.tsx, packages/types/uiComponents.ts, packages/ui-components/src/Card/CardCVC.tsx, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/types.ts
Some users want the functionality to visually redact the CVC value by setting the input type to "password"
```
evervault.ui.card({ redactCVC: true })
```
=> Add redactCVC option to set cvc input type to password

.changeset/orange-wombats-raise.md, .github/workflows/build-and-test.yml, examples/react-google-wallet/src/App.tsx, packages/types/uiComponents.ts, packages/ui-components/src/ApplePay/index.tsx, packages/ui-components/src/ApplePay/utilities.ts, packages/ui-components/src/Card/CardExpiry.tsx, packages/ui-components/src/GooglePay/utilities.ts, packages/ui-components/src/utilities/config.ts
Fix Google Pay and improve Transaction API ergonomics
- Use a static merchant ID value as provided by Google for Google Pay merchant.id
- Infer the merchant domain from the window for both Google and Apple Pay, remove the domain field from the merchant object.
=> dave/wallet api/merchant id domain changes

e2e-tests/browser-pre-release/index.html, e2e-tests/browser-pre-release/package.json, e2e-tests/browser-pre-release/playwright.config.js, e2e-tests/browser-pre-release/tests/encrypt.spec.js, e2e-tests/ui-components-pre-release/index.html, e2e-tests/ui-components-pre-release/package.json, e2e-tests/ui-components-pre-release/playwright.config.js, e2e-tests/ui-components-pre-release/tests/cards.spec.js, pnpm-lock.yaml
Allows us to run quick asserts against a specific instance of the browser SDK and UI Components. This will allow us to do prerelease testing before promoting a release to production.
```
VITE_EV_TEAM_UUID=... VITE_EV_APP_UUID=... VITE_API_KEY=... VITE_UI_COMPONENTS_URL=https://preview-url pnpm --filter=@repo/ui-components-pre-release-tests test-prerelease
VITE_EV_TEAM_UUID=... VITE_EV_APP_UUID=... VITE_API_KEY=... VITE_EVERVAULT_JS_URL=https://preview-url pnpm --filter=@repo/browser-pre-release-tests test-prerelease
```
=> Add packages for testing pre releases

.changeset/real-crews-shave.md, packages/browser/lib/ui/threeDSecure.ts, packages/types/uiComponents.ts, packages/ui-components/src/ThreeDSecure/index.tsx
We're marking all failures as failed on challenge. We should be more granular
Add new event to mark failure from fail on challenge and if received, send a boolean in the outcome patch request to CAPI
=> [EV-878] Propgate fail on challenge to CAPI'

.changeset/nervous-drinks-type.md, packages/ui-components/src/ThreeDSecure/BrowserFingerprint.tsx
We render different stages of the 3DS flow based on the state of the session. e.g browser fingerprint, challenge, etc. After each step, we refresh the session and trigger any callbacks or actions based on the new state. The browser fingerprint step has a 5 second timeout, however, the listener for this timeout isn't actually cleaned up until the browser fingerprint step is unmounted. This means that there is a race condition where it would be possible that even after a successful fingerprint, the timeout could still fire as the timeout wont be cancelled until the request to refresh the session has completed.
=> Clear timeout on fingerprint success

.changeset/happy-windows-fold.md, e2e-tests/ui-components/tests/cardDetails.spec.js, examples/collect-card-details/src/main.ts, packages/shared/src/useForm.ts
When setting a value for an input, we re run validation for any fields that have errors. This was reading from the errors state directly which can be out of date if called in the middle of a render. By using the setErrors callback syntax we will get the most up to date values.
I've also removed a line which skipped validating the current field in this setValue call. I'm not sure why this existed in the first place.
=> Fix bug causing errors to be cleared when using autoProgress

.changeset/ninety-candles-compare.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/card-validator/brands.ts, packages/card-validator/index.ts, packages/card-validator/test/validate-cvc.test.ts, packages/card-validator/types.ts
It's possible for older Amex cards to have both 3 and 4 digit CVCs.
=> Support 3 digit CVCs for amex

.changeset/seven-stingrays-divide.md, packages/types/uiComponents.ts
CAPI is now exposing some additional data from the raw Apple Pay payload
Refactoring of `EncryptedDPAN` type:
* Replaced the inline `token` definition with a new `PaymentToken` interface.
Enhancements to `EncryptedApplePayData` type:
* Removed `token` property since CAPI is returning this data as `networkToken`
* Added `networkToken` property, which includes `PaymentToken<"apple">` and `rawExpiry` string.
* Introduced new properties: `paymentDataType` and `deviceManufacturerIdentifier`.
=> Update Apple Pay types

.changeset/hip-buttons-whisper.md, .github/workflows/push.yml, .github/workflows/release.yml
We were performing releases by having one workflow push tags, and another trigger from them. This is not supported by GH to avoid infinite workflow recursion. To account for this, we need to have our release logic performed in the same flow which pushes tags.
- Make release workflow reusable and consume from workflow triggered on push
- Update changeset tag logic to produce a JSON array of all tags to publish, which is then provided as a matrix for the release workflow
- Update release workflow to expect a tag string, and not a fully qualified ref
=> Perform JS repo releases in a single execution to avoid workflow recursion

.github/workflows/push.yml
Release workflow was serializing JSON instead of deserializing it..
Use `fromJson` instead of `toJson`
=> chore: deserialize tags from json

.changeset/hip-buttons-whisper.md, e2e-tests/ui-components/CHANGELOG.md, e2e-tests/ui-components/package.json, examples/collect-card-details/CHANGELOG.md, examples/collect-card-details/package.json, examples/custom-theme/CHANGELOG.md, examples/custom-theme/package.json, examples/three-d-secure/CHANGELOG.md, examples/three-d-secure/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/ui-components/CHANGELOG.md, packages/ui-components/package.json
Updated release workflow appears correct following #594, so resetting the package state to remove the test deployment
Revert version packages PR and delete the changeset file included in CI refactor as a test (no-op) release.
=> Revert test deployments

.github/workflows/build-and-test.yml
Due to use calling build-and-test multiple times during a deployment workflow, the playwright reports are being uploaded multiple times which causes a workflow to fail. Obviously we need to actually improve the overall structure for these workflows but in the meantime we can overwrite the report.
=> Overwrite playwright report if conflict

.github/workflows/release.yml
The workflow was originally written with github tags as the trigger. This meant that it used contains checks everywhere for convenience, but this is now leading to false positives as we pass in explicit tag names.
Update all contains checks to use startsWith instead.
=> fix: Resolve papercuts in release workflow

.github/workflows/deploy-3ds.yml, .github/workflows/deploy-browser.yml, .github/workflows/deploy-inputs.yml, .github/workflows/deploy-ui-components.yml, .github/workflows/npm-publish.yml, .github/workflows/release.yml
Release job expects there to be a tag in `github.ref` but the workflow executes on push.
Pass release tag into the release workflow
=> Explicitly pass tag name in invoked release workflow

.github/workflows/deploy-3ds.yml, .github/workflows/deploy-browser.yml, .github/workflows/deploy-inputs.yml, .github/workflows/deploy-ui-components.yml
Release actions run against both staging and production so cannot guarantee that a tag name is always set
Mark tag name as not required
=> fix: tag name is not required to support staging deployments

.changeset/dull-ducks-occur.md, examples/apple-pay/src/main.ts, packages/browser/lib/ui/ApplePay/index.ts, packages/browser/lib/ui/ApplePay/types.ts, packages/browser/lib/ui/ApplePay/utilities.ts, packages/browser/lib/ui/index.ts, packages/browser/lib/utilities.ts
Apple Pay now supports third party browsers by rendering a modal window with a scannable code for the user to handle auth on their iPhone. However, this does not work for our current implementation due to it being inside of an iframe. The modal window opens inside of the iframe document and Apple provides no way to control where the modal is mounted.
Rewrite the Apple Pay component to render inside of the parent document. This is only possible because Apple Pay deals with tokens instead of raw PANs and so the compliance requirements do not require an iframe boundary. I've resisted the urge to do much refactoring to try to keep the API contracts and functionality the same as the other implementation.
For now I have nested this under a new `ui.applePayButton` component in order to keep the …
=> Support Apple Pay in third party browsers

.github/workflows/build-and-test.yml, .github/workflows/deploy-3ds.yml, .github/workflows/deploy-browser.yml, .github/workflows/deploy-inputs.yml, .github/workflows/deploy-ui-components.yml, .github/workflows/npm-publish.yml, .github/workflows/pull-request.yml, .github/workflows/push.yml, .github/workflows/release.yml
Potential race condition between staging and production builds due to artefacts sharing a namespace, and running in parallel.
- Give production release workflow a dependency on the staging release to avoid race condition
- Namespace the artefacts by environment
=> fix: make prod release happen after staging, and namespace artefacts to avoid conflicts

.github/workflows/e2e-test.yml
We currently have no ability to debug and identify flaky tests in CI
Add steps to run on e2e failure which upload the test report and results
=> Upload playwright report on e2e-test failure

.github/workflows/e2e-test.yml, .github/workflows/push.yml
e2e tests are misconfigured in workflow on push
Use correct url: keys.evervault.com
=> Use correct input for keys url in e2e tests on push

.github/workflows/publish-static-bundle.yml, .github/workflows/push.yml, .github/workflows/release.yml
The environments are used to select the appropriate variable value within Actions. The environment names in this repo leave a lot to be desired, and don't follow any strong structure (gated deployments are prefixed by the package name, some are suffixed by `-deploy`, others are just the stage). This should be cleaned up, but we need to get the CI working before that can happen.
Update static bundle workflow to accept explicit environment names for the package being released. This will be more reliable than the previous approach to try to build the environments based on other inputs.
=> Accept explicit environment names in static bundle publish workflow

.github/workflows/publish-static-bundle.yml
The input value is being inserted into the script verbatim, so cannot be handled as a string without quoting. This is causing a syntax error.
E.g. 
```js
const paths = /v2/preview/index.js.split(',').map(path => path.trim()).filter(path => path !== '');
return {
Paths: {
Quantity: paths.length,
Items: paths
}
};
```
Quote the invalidation paths in the script when preparing the cloudfront payload
=> Quote the invalidation paths in action script

.github/workflows/publish-static-bundle.yml, e2e-tests/ui-components/tests/threeDSecure.spec.js
More teething issues with new workflows, and trying to address flaky tests
- Pass caller reference to the cloudfront invalidation call
- Remove recursive flag being passed to html file upload
- Increase timeout on the 3ds test to reduce retries
=> Further workflow fixes

.github/workflows/push.yml
Merges without changesets are marked as failed in CI because there are no tags given in the release job's matrix.
Add additional output variable to show the number of tags, and make the release job conditional on it to prevent jobs being inaccurately marked as failed.
=> Check that there are tags to release before scheduling release job

.changeset/gentle-elephants-study.md, packages/react-native-v2/android/build.gradle
Sets the minimum SDK versions, as advised by React Native:
https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture#updates-to-minimum-ios-and-android-sdk-requirements
- Updates the SDK versions in `build.gradle`
=> Update SDK versions for React Native Android side

.github/workflows/npm-publish.yml, .github/workflows/publish-static-bundle.yml
Releases being created on publish contain the entirety of a packages changes instead of the details for the release in question
For a release commit, take the diff of the changelog file, strip the diff formatting, and use it as the changelog content.
=> fix: parse out the changelog relevant to the specific release

.changeset/chatty-hairs-help.md, packages/react-native-v2/src/Card/Root.test.tsx, packages/react-native-v2/src/Card/schema.ts, packages/react-native-v2/src/Card/types.ts, packages/react-native-v2/src/Card/utils.ts
Our brand validation was included on a schema `superRefine`, which doesn't seem to be called with hook form resolvers (since each field is validated individually).
This moves the validation over to a `refine`, since we technically only need the number field value
- Switch from `superRefine` on schema object to `refine` on number field
- Add test to confirm expected functionality
- Add jsdoc comment to `acceptedBrands` prop for more info
=> Fix `acceptedBrands` validation for `Card` component

.github/workflows/npm-publish.yml, .github/workflows/publish-static-bundle.yml
The changelog script errors due to its handling of multiline output
Update script for deriving the changelog for a release to support multiline output
=> fix: correct changelog script to support multiline output

.changeset/big-planets-own.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/browser/lib/ui/card.ts, packages/react/lib/ui/Card.tsx, packages/types/uiComponents.ts, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/types.ts
Some Amex cards can have 3 digit CVC codes, however, not all payment gateways support 3 digit Amex CVCs.
Introduce a new `allow3DigitAmexCVC` option to the card component to allow users to disable support for 3 digit Amex CVCs.
```js
evervault.ui.card({
allow3DigitAmexCVC: false
})
```
=> Add allow3DigitAmexCVC option to Card component

.github/workflows/npm-publish.yml, .github/workflows/publish-static-bundle.yml
Pre-release tests are running against the wrong projects
- Update workflow to split between browser and ui-components
- Refine changelog logic
=> fix: correct prerelease steps in workflows to run the correct harness

.github/workflows/npm-publish.yml, .github/workflows/publish-static-bundle.yml
The step that creates the changelog requires the tags to be fetched in advance so we can distinguish between new and existing packages, and decide which commits to diff.
Add fetch-tags: true to the checkout
=> fix: add fetch-tags: true to changelog gen step

.changeset/witty-years-watch.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/utilities.ts
We need to pass the `allow3DigitAmexCVC` option through to the payload formatting so that it can correctly set the isComplete field.
=> Set isComplete to false for 3 digit Amex CVCs when disabled.

.github/workflows/npm-publish.yml, .github/workflows/publish-static-bundle.yml
Using `git tag -l` will only see locally fetched tags. We want to be able to check if there are existing tags before running an expensive fetch.
- Update to use `ls-remote` to locate tags for the current package
- Fetch all tags before diffing if needed.
=> Update create release to use ls-remote

.changeset/spicy-peas-rhyme.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/ui-components/src/Card/index.tsx
Missed this in the previous PR because the `validate` method has its own use of the `changePayload` method.
=> Correctly set isComplete in validate response for 3 digit amex CVCs

.changeset/strong-kangaroos-reflect.md, packages/browser/lib/ui/googlePay.ts, packages/types/package.json, packages/types/uiComponents.ts, packages/ui-components/src/GooglePay/index.tsx, packages/ui-components/src/GooglePay/types.ts, packages/ui-components/src/GooglePay/utilities.ts, pnpm-lock.yaml
Adds support for requesting billing address information with Google Pay.
You can now collect billing address information using the `billingAddress` option.
```js
const googlePay = evervault.ui.googlePay(transaction, {
billingAddress: true,
process: async (payload) => {
console.log(payload.billingAddress)
}
});
```
You can also specific the address format and request a phone number by using an object instead of a boolean.
```js
const googlePay = evervault.ui.googlePay(transaction, {
billingAddress: {
format: 'MIN',
phoneNumber: true
},
process: async (payload) => {
console.log(payload.billingAddress)
}
});
```
=> Add billing address support to Google Pay

.changeset/shiny-dodos-hunt.md, examples/expo/src/screens/Card.tsx, packages/react-native-v2/src/Card/Cvc.tsx, packages/react-native-v2/src/Card/Number.test.tsx, packages/react-native-v2/src/Card/Number.tsx, packages/react-native-v2/src/Input.test.tsx, packages/react-native-v2/src/Input.tsx
This PR enables mask obfuscation for the `Card.Number` and `Card.Cvc` components
- Adds new `obfuscateValue` prop to `EvervaultInput`, which accepts a boolean or obfuscation character
- Adds "obfuscate on blur" example to Expo app
- Convert `<Controller>` usage to `useController`
=> Add mask obfuscation

.changeset/mean-masks-burn.md, examples/react/src/App.tsx, packages/react/lib/load.ts, packages/react/lib/main.tsx, packages/react/lib/ui/Card.tsx, packages/react/lib/ui/Pin.tsx, packages/react/lib/ui/Reveal.tsx, packages/react/lib/ui/RevealCopyButton.tsx, packages/react/lib/ui/RevealText.tsx, packages/react/lib/ui/ThreeDSecure.tsx, packages/react/lib/useEvInstance.ts, packages/react/lib/useEvervault.ts
Previously, our browser SDK loading logic would never retry if it failed to load once. This is an issue if the script fails to load initially but is then made available later
~While this PR does not add explicit functionality to force a retry, it does allow for retries when the `EvervaultProvider` component is remounted (e.g. a `key` is changed)~
**Edit:** in addition to automatic retries on mount, we've also added a `reload` function to the `EvervaultProvider` ref so the script can retry a load without needing to remount the tree
- Move browser script loading to separate file, add handy hook `useEveraultClient`
- Move to a promise map to allow for multiple load promises to happen concurrently
- Adds new `reload` function via an `EvervaultProvider` ref for manual reloads
- Add new …
=> Allow for browser SDK load retries in `@evervault/react`

.github/workflows/publish-static-bundle.yml
Most recent deployment surfaced a bug in our prod release flow for static bundles — a cancelled preview would trigger a production release due to the conditions being too lenient.
The production release was run on the condition of `always() && !failure()` after the preview. This didn't account for a cancelled preview, which occurs in the event of a parallel job failing.
- Update conditions for release 🧑‍⚖️ 
- Add very explicit comments to motivate the weird condition.
=> chore: ensure the live deployment doesn't proceed after a parallel job cancels the preview

.changeset/hip-actors-explode.md, examples/react-google-wallet/src/App.tsx, packages/types/uiComponents.ts, packages/ui-components/src/GooglePay/index.tsx
We have access to it, at least one customer wants it, so lets expose it.
Set the card.lastFour field of the Google Pay object from `data.paymentMethodData.cardDetails`. This should be the lastFour. If anything other than 4 digits, we try to parse 4 digits from this string. If that fails fallback to attempting to parse if from `paymentMethodData?.description` which also usually contains the last four.
=> PAY-94 Expose last 4 of underlying card for Google Pay

.changeset/curly-walls-protect.md, packages/browser/lib/ui/ApplePay/index.ts, packages/browser/lib/ui/ApplePay/utilities.ts
We should allow a user to implement logic to update the transaction before showing the Apple Pay modal, for example to offer a sign-up discount or other promotion.
Add an `onClick` callback to the Apple Pay config, which returns a Promise of `{ amount?: number; lineItems?: TransactionLineItem[]; }` which are used to update the transaction.
See video below for an example implementation:
https://github.com/user-attachments/assets/0e208e57-6e2b-44e1-b566-c66fec510fa4
=> PAY-28 Add prepareTransaction callback for Apple Pay

e2e-tests/crypto-harness/package.json
Changesets is attempting to create a release for the crypto harness as it has a version value. This is unexpected based on their documentation, but is currently blocking CI on master so deleting version to unblock.
Remove version for private package
=> fix: remove version from harness to avoid being included in changeset

.changeset/plenty-dogs-shop.md, examples/react-google-wallet/src/App.tsx, packages/browser/lib/ui/ApplePay/index.ts, packages/browser/lib/ui/ApplePay/types.ts, packages/browser/lib/ui/ApplePay/utilities.ts
The typing of the parameter to the onShippingChange callback was pretty poor.
Parse the shipping address out of the event target and pass that to the callback.
=> Improve the types for onShippingAddressChange

.changeset/proud-mails-return.md, packages/card-validator/index.ts, packages/card-validator/test/validate-number.test.ts
We should return the BIN as soon the input length is sufficient so that BIN dependent use cases can be enabled without collecting the full card
=> Expose BIN on card onchange event as soon as identifiable

.changeset/fair-mugs-notice.md, e2e-tests/ui-components/tests/cardDetails.spec.js, packages/browser/lib/ui/card.ts, packages/react/lib/ui/Card.tsx, packages/types/uiComponents.ts, packages/ui-components/src/Card/index.tsx, packages/ui-components/src/Card/translations.ts, packages/ui-components/src/Card/types.ts
Adds a new `validation` option to Card Collection to allow users to customise validation logic.
For now this just introduces an option for adding regex validation to the card holder name, however, we can expand this object in the future to suport more options.
```
evervault.ui.card({
validation: {
name: {
regex: /^[^0-9]+$/
}
}
})
```
=> Validation option for cardholder name

.github/workflows/publish-static-bundle.yml, .github/workflows/revert-release.yml
Using github oidc instead of access keys
=> Using github oidc instead of access keys

.changeset/seven-elephants-poke.md, packages/ui-components/src/utilities/useMask.ts, packages/ui-components/src/utilities/userAgent.ts
There seems to be a known bug where autofilling elements on chrome on iOS does not correctly emit onChange events inside of React.
https://issues.chromium.org/issues/41371116
Setup native listeners for the required events only when on chrome on iOS.
=> Fix autofill on chrome on iOS

.github/workflows/publish-static-bundle.yml
Action needs write permissions to be able to create a github release
Update permissions requested by action
=> Grant write permissions for static bundle release

.changeset/serious-beds-do.md, .github/workflows/react-native.yml, packages/react/lib/main.tsx, packages/react/lib/ui/Card.tsx
This will allow for providing access to methods on the underlying card instance from the JS SDK. e.g the `validate` method to force validation.
=> Add imperative handle ref to Card component in React SDK

.changeset/silly-pants-relate.md, packages/ui-components/src/GooglePay/index.tsx
The locale field on the GooglePay button config is not passed to the PaymentsClient
Fix it.
=> Fix GooglePay locale
