evervault/evervault-js

- lib/v1/config.js
- lib/v1/core/crypto.js
- lib/v1/curves/base.js
- lib/v1/curves/index.js
- lib/v1/curves/p256.js
- lib/v1/index.js
- lib/v1/utils/asn1.js
- lib/v1/utils/crypto.js
- lib/v1/utils/index.js
Update browser SDK with support for NIST-P256 curve
Tested encrypted outputs in a cage
> Update browser SDK with support for NIST-P256 curve

- lib/v1/config.js
- lib/v1/core/index.js
- lib/v1/core/inputs.js
- lib/v1/index.js
We need to provide iframes for collecting card details for customers' PCI requirements
Added a function to generate an input which inserts the iframe into the client's page and returns a hook and method for getting the encrypted data
https://evervault.notion.site/evervault/Evervault-Inputs-59655cf4f0794faca8c255ccc73703b4
> Adding Input provision and handling

- lib/v1/core/inputs.js
- lib/v1/index.js
Encryption should be completed within iframe
Removed encryption of input results
> Removing encryption for Inputs at SDK level, moving to iframe

- lib/v1/core/http.js
Last commits didn't have semantic release formatting
Minor change to facilitate release
> feat(sdk) Releasing js sdk

- lib/v1/core/crypto.js
Releasing sdk
Minor change to facilitate release
> feat(sdk): Releasing js sdk

- lib/v1/core/inputs.js
Incorrect id was being used for iframe src param
Used teamId from config
> fix(inputs): using teamId in iframe src

- README.md
Id did not match the div
Corrected div id in evervault.inputs()
> docs(inputs): correcting div id

- README.md
Docs need to explain how to use the js sdk with apps
> docs: Update README for v2

- lib/v1/config.js
- lib/v2/config.js
- lib/v2/core/inputs.js
Change event was being filtered because it was comparing a full url to an origin in js.
Added a separate config option for origin which is stable to match against.
> fix: inputs change event

- .github/workflows/test.yml
- .gitignore
- README.md
- lib/utils/crypto.js
- lib/utils/datatypes.js
- lib/v2/config.js
- lib/v2/core/crypto.js
- lib/v2/core/http.js
- lib/v2/index.js
- package-lock.json
- package.json
- test/encryption.js
- test/utils.js
Javascript SDK needs to add support for the encryption of Files in the browser.
- Added logic to check if an object passed in to `evervault.encrypt()` is a file. If so it is encrypted per our File Encryption specification.
> feat: Ability to encrypt files in the Evervault Javascript SDK

- README.md
- lib/utils/calculateHeight.js
- lib/utils/constructSource.js
- lib/v1/core/inputs.js
- lib/v1/index.js
- lib/v2/core/inputs.js
- lib/v2/index.js
The user should be able to set the labels they wish to use in their iframe, in particular as it will allow localization
Passing all config fields from Inputs initialization to iFrame
> feat: adding custom label handling for inputs

- package-lock.json
- package.json
Upgrade webpack and webpack cli to `5.0`
- Update dependencies
> refactor: Upgrade webpack and webpack cli

- package-lock.json
- package.json
Reverts evervault/evervault-js#47
> Revert "refactor: Upgrade webpack and webpack cli"

- README.md
- Flag to disableCVV is not available for Inputs 
- Added new flag
> Add new disableCVV flag to inputs

- .github/workflows/build-and-deploy-staging.yml
- .github/workflows/release.yml
moving from netlify
adding action to build and deploy to staging s3, no code changes
> fix: add action to deploy to staging

- .github/workflows/build-and-deploy-staging.yml
Use org level secrets for deployment
- Update secret values
> refactor: use org level secret

- .github/workflows/build-and-deploy-staging.yml
Build is failing for node-18
- Commented out workflow for now
> refactor: comment out staging workflow

- .github/workflows/release.yml
> fix: remove npm publishing

- .github/workflows/deployment.yml
Incorrect workflow name was used in a step
Used the correct name
> Fix workflow name import

- .github/workflows/deployment.yml
> fix: wrong job name

- README.md
There are new CSS styling options available for Evervault Inputs
- Update JS inputs docs with new flags
> docs: add font customization to the README

- .github/workflows/aws-build-and-deploy.yml
> fix: job names

- README.md
New `inputBoxShadow` property added
- Added property to the docs
> docs: update inputs with box-shadow change

- .github/workflows/aws-generic-deploy.yml
Action workflow is missing dollar signs
Add dollar signs
> Fix V1 AWS deploy

- .github/workflows/aws-build-and-deploy.yml
> fix: missing version

- .github/workflows/aws-build-and-deploy.yml
- .github/workflows/playwright.yml
- .github/workflows/test.yml
- package.json
- pnpm-lock.yaml
> fix: update lockfile to pnpm

- .changeset/unlucky-pandas-hope.md
- packages/browser/lib/utils/index.js
- packages/browser/lib/utils/uuid.js
uuid util file isn't used in the code and is just dead noise.
Remove uuid util file
> Remove unused uuid util

- README.md
Need to document release process
Described the release process
> Create README.md with version docs

- .changeset/cold-papayas-admire.md
- packages/browser/lib/core/inputs.js
> feat: add is loaded status for inputs iframe

- .changeset/happy-cups-peel.md
- .github/workflows/push.yml
- .github/workflows/release.yml
- packages/browser/lib/core/inputs.js
- packages/browser/scaffold.js
Missed a commit to fix a syntax error with the inputs loading status. I'm also disabling inputs deployment until the old repo is archived.
> Fix syntax error for inputs loading status

- .changeset/twenty-feet-bow.md
- packages/browser/lib/config.ts
- packages/browser/lib/main.ts
Do you have a minute to talk about our lord and savior Typescript.
Actually typecheck the `main.ts` file. Add pretty JSDoc to the public facing methods.
> [ETR-884] Move main entrypoint to typescript

- .changeset/fair-snails-promise.md
- packages/browser/package.json
- packages/inputs/vite.config.mts
SRI Plugin was not giving us hashes due to incorrect configuration
Corrected the config
> Fix SRI Path wierdness

- .changeset/gentle-chicken-brush.md
- package.json
- packages/browser/lib/main.ts
- packages/browser/package.json
- packages/browser/vite.config.mts
- pnpm-lock.yaml
- chore: add new typings
- chore: changeset
> Add type declarations for browser sdk.

- turbo.json
> fix: turbo task update

- .github/workflows/push.yml
> Missing .yml extention in workflow

- packages/browser/README.md
> fix: add documentation for onInputsLoaded

- .changeset/dirty-glasses-matter.md
- packages/browser/lib/config.ts
- packages/browser/lib/core/http.ts
- packages/browser/lib/main.ts
- packages/browser/lib/utils/errors.ts
- packages/browser/package.json
- packages/browser/test/basic.test.ts
- pnpm-lock.yaml
Add decrypt using a token for front end decrypts
Add decrypts and tests
> Add decrypt

- .changeset/curvy-ghosts-sing.md
- packages/browser/lib/core/http.ts
- packages/browser/test/basic.test.ts
Should just be "Token"
Changed it
> change auth scheme

- packages/react/README.md
- packages/react/lib/main.tsx
- packages/react/package.json
- pnpm-lock.yaml
The React readme had some broken links and invalid documentation.
- Fix broken links
- Fix typos
- Update syntax in examples
> Improve React Readme

- .changeset/twenty-monkeys-refuse.md
- packages/browser/lib/core/inputs.ts
- packages/browser/lib/main.ts
- packages/browser/lib/utils/constructSource.ts
- packages/inputs/src/InputElementsManager.ts
- packages/inputs/src/index.ts
- packages/inputs/src/styles.css
- packages/react/lib/main.tsx
Evervault Reveal lets customers view data Cardholder data through an iframe
> feat: add evervault reveal

- .changeset/cyan-meals-worry.md
- packages/inputs/src/index.ts
reveal loading before it has fetched is strange
> fix: dont load reveal until fetched

- .changeset/spotty-baboons-hear.md
- packages/inputs/src/styles.css
> remove labels from reveal

- .changeset/chilled-pumpkins-act.md
- .changeset/new-items-swim.md
- .changeset/perfect-wombats-matter.md
- .changeset/silent-plums-tell.md
- packages/browser/lib/core/inputs.ts
- packages/inputs/index.html
- packages/inputs/src/index.ts
- packages/inputs/src/styles.css
- packages/react/lib/main.tsx
- pnpm-lock.yaml
Slight DX refinements for Inputs and Reveal
- Improve compatibility with Chrome on Darkmode themed systems
- Fix inputs/reveal auto-resize behaviour
- Default to auto-resize Inputs and Reveal in the react sdk
> improve reveal/inputs dx

- .changeset/dirty-dolphins-behave.md
- .github/workflows/build-and-test.yml
- .github/workflows/npm-publish.yml
- .github/workflows/release.yml
- packages/react/package.json
releases for react are broken
fix the workflow
> fix react release

- .changeset/quiet-rocks-rhyme.md
- packages/browser/lib/core/inputs.ts
- packages/browser/lib/main.ts
- packages/react/README.md
- packages/react/lib/main.tsx
Need to finish off Reveal in the React SDK
Add docs for it and fix an issue with Next.JS SSR
> Add docs and fix requests for SSR Reveal

- .changeset/silly-chairs-joke.md
- packages/inputs/src/index.html
unintended dark mode in some places
remove color scheme
> rm color scheme

- .changeset/fair-bottles-collect.md
- packages/browser/README.md
- packages/browser/lib/core/inputs.ts
- packages/browser/lib/utils/constructSource.ts
- packages/inputs/src/app/customLabelsHandler.ts
- packages/inputs/src/app/customStylesHandler.ts
- packages/inputs/src/app/index.ts
- packages/inputs/src/app/styles.css
- packages/inputs/src/reveal.html
Adding labels and custom styles to Evervault Reveal
Added them
> add labels and custom styles

- .changeset/thirty-rules-chew.md
- packages/inputs/src/app/styles.css
This PR introduces a new template named `material-sling`.
https://github.com/evervault/evervault-js/assets/3931618/c4b3bd77-b040-4637-9f76-39eda3a68fb0
A new template was created.
> Add new material-sling template

- packages/ui-components/package.json
Change set handles the version bump so it being 1 meant we were going to release version 2.
> Set package version to 0.0.0 for ui-components

- .github/workflows/release.yml
Updates the release flow to call the workflow for deploying UI components to production.
> Add production deployment action for UI Components

- .github/workflows/build-and-test.yml
- .github/workflows/release.yml
- pnpm-lock.yaml
Want to use card validator package in react native sdk
add it to release workflows
> Publish @evervault/card-validator to npm

- packages/card-validator/package.json
- packages/card-validator/vite.config.mts
- pnpm-lock.yaml
Nothing getting built to dist
add vite build conf
> Create card validator build config

- .github/workflows/npm-publish.yml
> switch to updated token

- packages/card-validator/index.ts
- packages/card-validator/package.json
- packages/card-validator/vite.config.mts
- packages/ui-components/src/Card/utilities.ts
Blocking npm release
populate package.json
> add card validator details to package.json

- packages/card-validator/package.json
> Bump card-validator package.json version

- packages/react-native/package.json
> Bump react-native pkg ver

- .changeset/seven-buttons-crash.md
- packages/shared/package.json
- packages/themes/package.json
- packages/types/package.json
> mark internal pkgs as private

- .changeset/tidy-bikes-switch.md
- .github/workflows/build-and-test.yml
- .github/workflows/release.yml
- packages/card-validator/package.json
- packages/react-native/example-usage/ios/Podfile.lock
- packages/react-native/package.json
- packages/react-native/src/components/Card/Card.tsx
- packages/react-native/src/components/Card/context.tsx
- packages/react-native/src/components/Card/index.ts
- packages/react-native/src/components/Card/types.ts
- packages/react-native/src/components/Card/utilities.ts
- packages/react-native/src/components/index.ts
- packages/react-native/src/components/useForm.tsx
- packages/react-native/src/index.tsx
- packages/react-native/src/native.ts
- packages/react-native/src/sdk.ts
- packages/shared/package.json
- packages/ui-components/package.json
- pnpm-lock.yaml
Vite doesn't support react native
Vendor stuff from shared packages until we figure out something better
Also try release from workflow
> Stop using shared packages in react native

- .changeset/loud-horses-sparkle.md
- packages/react-native/package.json
> Add RN package to monorepo build script

- .changeset/cool-mice-type.md
- packages/react-native/package.json
- pnpm-lock.yaml
When the package gets installed it can't resolve card-validators because it's not a direct dep
> move card-validator to direct deps

- .changeset/fresh-donkeys-promise.md
- .changeset/selfish-lemons-joke.md
- packages/react-native/package.json
- packages/react-native/src/components/Card/Card.tsx
- packages/react-native/src/components/Card/CardCVC.tsx
- packages/react-native/src/components/Card/CardExpiry.tsx
- packages/react-native/src/components/Card/CardHolder.tsx
- packages/react-native/src/components/Card/CardNumber.tsx
Build for umd is creating js files referencing React instead of _react.
Import it in components
> Fix React JSX in module build

- .changeset/afraid-bobcats-drop.md
- packages/react-native-example/App.tsx
- packages/react-native/README.md
- packages/react-native/src/components/Card/Card.tsx
> Remove the onComplete event because it's confusing

- .changeset/beige-tools-smash.md
- packages/ui-components/src/Form/index.tsx
There is two much space between the asterisk and the last letter  
- Remove the space
> fix: remove spacing from required

- .changeset/stupid-eels-speak.md
- .github/workflows/build-and-test.yml
- packages/browser/lib/core/crypto.ts
Don't need metadata code for files
Remove it
> remove dead code

- package.json
- packages/react-native-example/App.tsx
- packages/react-native-example/components/CardDebug.tsx
- packages/react-native-example/components/CardForm.tsx
- packages/react-native-example/ios/Podfile.lock
- packages/react-native/src/components/Card/Card.tsx
- pnpm-lock.yaml
Vulnerable downstream
Force override the vulnerable package
Also added some debug components to the example, that are useful in dev
> Fix react-native vulnerability

- .changeset/orange-roses-grin.md
Vulnerabilities resolved
Release it
> Release new react native version

- README.md
> Fix dead reactjs SDK link

- .changeset/dry-mayflies-invent.md
- packages/ui-components/src/ThreeDSecure/utilities.ts
The 3DS session endpoint required content type to be set.
> Add Content type application/json to header

- .changeset/spotty-stingrays-warn.md
- packages/browser/lib/ui/threeDSecure.ts
- packages/types/uiComponents.ts
- packages/ui-components/src/ThreeDSecure/BrowserFingerprint.tsx
- packages/ui-components/src/ThreeDSecure/ChallengeFrame.tsx
- packages/ui-components/src/ThreeDSecure/IssuerFingerprint.tsx
- packages/ui-components/src/ThreeDSecure/Overlay.tsx
- packages/ui-components/src/ThreeDSecure/index.tsx
- packages/ui-components/src/ThreeDSecure/types.ts
- packages/ui-components/src/ThreeDSecure/utilities.ts
Adds [3DS method](https://docs.3dsecure.io/3dsv2/3dsmethod.html) support to the ThreeDSecure UI Component
> Add support for 3DS Method

- .changeset/ten-colts-cry.md
- packages/react-native-example/components/CardForm.tsx
- packages/react-native/src/components/Card/Card.tsx
- packages/react-native/src/components/Card/CardCVC.tsx
- packages/react-native/src/components/Card/CardExpiry.tsx
- packages/react-native/src/components/Card/CardHolder.tsx
- packages/react-native/src/components/Card/CardNumber.tsx
- pnpm-lock.yaml
useful for styling text inputs
expose
> Allowing passing of onBlur prop in RN sdk

- e2e-tests/ui-components/tests/threeDSecure.spec.js
Add playwright tests for threeDSecure component.
> Add tests for ThreeDSecure UI Component

- .github/workflows/build-and-test.yml
- .github/workflows/deploy-3ds.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
Mismatch between staging and prod
Add "aws" to align with production names 
Also moved to use build step and artifacts
> Fix secret names in 3ds staging action so they match production

- .github/workflows/deploy-3ds.yml
Not needed
Remove it. 
Note: I have another WIP branch open to move tests to staging but would be good to get 3ds out
> Remove 3ds working directory from action

- .changeset/funny-dots-laugh.md
- packages/3ds/src/main.ts
Need to release 3ds package to deploy to prod
Add changeset
> Add changeset for 3ds release

- .changeset/brown-candles-marry.md
- packages/react-native/src/components/3DS/config.ts
I had removed testing one previously but accidently committed again with last batch of changes -_-
Update to 3ds.evervault.com
> Update default 3DS URL

- .changeset/config.json
Reverts evervault/evervault-js#449
> Revert "Dont bump private packages version"

- .changeset/sharp-toes-sin.md
- .env.example
- examples/react-google-wallet/src/App.tsx
- packages/types/uiComponents.ts
- packages/ui-components/src/ApplePay/index.tsx
- packages/ui-components/src/ApplePay/utilities.ts
- packages/ui-components/src/GooglePay/index.tsx
- packages/ui-components/src/GooglePay/utilities.ts
- packages/ui-components/src/utilities/useMerchant.ts
Improve the DX of the Wallet API.
Get the required merchant details from the new merchant frontend API.
> Replace Wallet API merchant object with merchantId field

- .github/workflows/deploy-browser.yml
- .github/workflows/deploy-ui-components.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
Want to validate that we havent broken anything before releasing code
Update the ui-comp and browser deploy workflows to:
- use inherited secrets
- Push builds to preview
- run preflights on the preview
> Run Preflights check on browser and ui-compontent with preview releases

- e2e-tests/browser-pre-release/tests/encrypt.spec.js
- e2e-tests/ui-components-pre-release/tests/cards.spec.js
Tests are failing in release workflow
Update API Key env key in tests
> Update API KEY env var

- .changeset/new-cheetahs-run.md
- packages/browser/lib/ui/threeDSecure.ts
Casing is wrong on the outcome update
Update
> Fix casing on aborted-on-challenge

- packages/react-native-v2/package.json
> Down-version React Native SDK to v1

- .changeset/modern-moles-rest.md
- .github/workflows/build-and-test.yml
- packages/browser/lib/ui/ApplePay/index.ts
- packages/browser/lib/ui/ApplePay/utilities.ts
Also removes unused `exchangeApplePaymentData` function.
> Use configured API url from client instead of environment variable

- .changeset/moody-carrots-search.md
Patch releases to update the bundles types to match the latest browser SDK deployments
> Create a release for @evervault/react and @evervault/js

- .github/workflows/npm-publish.yml
- .github/workflows/release.yml
Some teething issues surfaced in the first release for the new react native package
- Account for react-native-v2 file path mapping in the changelog step
- Update react sdk to check that its not a false positive caused by a react native release
> Further tweaks on release process for react native

- .changeset/quiet-roses-fry.md
> Add changelog

- .github/workflows/publish-static-bundle.yml
- .github/workflows/revert-release.yml
Adding token write permissions to workflows
> Adding token write permissions to workflows
